require:
  - rubocop-rspec_rails
  - rubocop-capybara

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - "spec/system/*"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/system/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

AllCops:
    NewCops: enable
